modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="digitalstorage"
version="${version}"
displayName="汤姆的简易存储：云上加仓"
authors="kehai"
logoFile="assets/digitalstorage/icon.png"
description='''Player-owned storage volumes exposed through lightweight, linkable accessors.'''

[[dependencies.digitalstorage]]
modId="forge"
mandatory=true
versionRange="[47.4.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.digitalstorage]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.digitalstorage]]
modId="toms_storage"
mandatory=true
versionRange="[1.7.1,)"
ordering="AFTER"
side="BOTH"
